unix {
  nodaemon
  interactive
  log /var/log/vpp.log
  full-coredump
  cli-listen /run/vpp/cli.sock
  exec /etc/vpp/vpp_cli.conf
}

api-trace {
  on
}

socksvr {
  socket-name /run/vpp/api.sock
}


plugins {
  plugin default { disable }
  plugin dpdk_plugin.so { enable }
  # plugin firewall_plugin.so { enable }
  # plugin flowtable_plugin.so { enable }
  # plugin bng_policer_plugin.so { enable }
  # plugin agf_encap_plugin.so { enable }
  # plugin memif_plugin.so { enable }
}

cpu {
  main-core 32
  
  # B1.1 - 1WT/ 0HT
  corelist-workers 33

  # B1.1 - 1WT/ 1HT
  # corelist-workers 33
  # corelist-hqos-threads 52

  # B1.1 - 8WT/ 0HT
  # corelist-workers 33,34,35,36,37,38,39,40

  # B1.1 - 8WT/ 1HT
  # corelist-workers 33,34,35,36,37,38,39,40
  # corelist-hqos-threads 52
  
  # B1.1 - 8WT/ 8HT
  # corelist-workers 33,34,35,36,37,38,39,40
  # corelist-hqos-threads 52,53,54,55,56,57,58,59
}


memory {
  main-heap-size 500M
  main-heap-page-size 1G
}

buffers {
   default data-size 2048
   page-size default-hugepage
}

dpdk {
  no-multi-seg
  no-tx-checksum-offload

  dev default {
    num-rx-desc 4096
    num-tx-desc 4096
  }

  dev 0000:b3:01.0 {
    name if0

    # B1.1 - 1WT/ 0HT
    num-rx-queues 1 
    num-tx-queues 1 

    # B1.1 - 1WT/ 1HT
    # num-rx-queues 1 
    # num-tx-queues 1 
    # hqos { hqos-thread 0 }

    # B1.1 - 8WT/ 0HT
    # num-rx-queues 8 
    # num-tx-queues 1 

    # B1.1 - 8WT/ 1HT
    # num-rx-queues 8 
    # num-tx-queues 1 
    # hqos { hqos-thread 0 }
  }
}

logging {
  ## Available severity levels:
  ## emerg|alertcrit|err|warn|notice|info|debug|disabled

  default-log-level info
  default-syslog-log-level info
}
