set interface ip address if0  192.168.0.0/20
set interface ip address if0  10.0.0.1/24

set ip neighbor count 4097 if0 192.168.0.1 dead.0000.babe  static
set ip neighbor count 1 if0 10.0.0.0 aead.0000.0000  static

set interface state if0  up
