unix {
  nodaemon
  interactive
  log /var/log/vpp.log
  full-coredump
  cli-listen /run/vpp/cli.sock
  exec /etc/vpp/vpp_cli_l3conf.conf
}

api-trace {
  on
}

socksvr {
  socket-name /run/vpp/api.sock
}


plugins {
  plugin default { disable }
  plugin dpdk_plugin.so { enable }
  plugin firewall_plugin.so { enable }
  plugin flowtable_plugin.so { enable }
  plugin bng_policer_plugin.so { enable }
  plugin agf_encap_plugin.so { enable }
  plugin memif_plugin.so { enable }
}

cpu {
  main-core 48
  corelist-workers 49,50
  corelist-hqos-threads 51
}


memory {
  main-heap-size 500M
  main-heap-page-size 1G
}

buffers {
   default data-size 2048
   page-size default-hugepage
}

dpdk {
  no-multi-seg
  no-tx-checksum-offload

  dev default {
    num-rx-desc 4096
    num-tx-desc 4096
  }

  ## Downlink - Instance 0 
  dev 0000:b3:01.7 {
    name if0
    num-rx-queues 1 
    num-tx-queues 2 
    hqos { hqos-thread 0 }
  }
  ## Uplink - Instance 0 
  dev 0000:b3:02.0 {
    name if1
    num-rx-queues 1
    num-tx-queues 1
  }
}

logging {
  ## Available severity levels:
  ## emerg|alertcrit|err|warn|notice|info|debug|disabled

  default-log-level info
  default-syslog-log-level info
}
