##### DOWNLINK INTERFACES ####

set interface ip address if0  192.168.16.0/20
set interface ip address if0  10.1.0.1/24

set ip neighbor count 4097 if0 192.168.16.1 dead.0000.babe  static

set interface state if0  up

allowlist set if0 enable
exec /etc/vpp/bulk_configs/bng/allowlist.conf
flowtable_ip4 intf if0 
exec /etc/vpp/bulk_configs/bng/flowtables.conf
encap qinq intf if0 
exec /etc/vpp/bulk_configs/bng/encap.conf

# ##### UPLINK INTERFACES ####
# 
set interface ip address if1  10.0.0.1/24
# 
set interface state if1  up
# set interface state if3  up
# set interface state if5  up
# set interface state if7  up
# set interface state if9  up
# set interface state if11 up
# set interface state if13 up
# set interface state if15 up
# 
# # set ip neighbor count 4097 if1 192.160.0.1 dead.beef.babe
# # set ip neighbor count 1 if1 10.1.0.2 deac.ceec.babe
# # 
# # allowlist set if1 enable
# # exec /etc/vpp/bulk_configs/pipeline_complexity/allowlist.conf
# # flowtable_ip4 intf if1 
# # exec /etc/vpp/bulk_configs/pipeline_complexity/flowtables.conf
# # encap qinq intf if1 
# # exec /etc/vpp/bulk_configs/pipeline_complexity/encap.conf
