unix {
  nodaemon
  interactive
  log /var/log/vpp.log
  full-coredump
  cli-listen /run/vpp/cli.sock
  exec /opt/vpp_cli.conf
}

api-trace {
  on
}

statseg {
  size 1G
}

socksvr {
  socket-name /run/vpp/api.sock
}

plugins {
  plugin default { disable }
  plugin dpdk_plugin.so { enable }
  plugin firewall_plugin.so { enable }
  plugin flowtable_plugin.so { enable }
  plugin bng_policer_plugin.so { enable }
  plugin agf_encap_plugin.so { enable }
}

cpu {
  main-core MAIN_CORE
  corelist-workers UPLINK_CORE,DOWNLINK_CORE
  corelist-hqos-threads HQOS_CORE
}

memory {
  main-heap-size 1000m
  main-heap-page-size 2m
}

dpdk {
  ## Uplink VF
  ## worker core(s): UPLINK_CORE (core list index 0)
  #
  dev UPLINK_PCI {
    workers 0
  }

  ## Downlink VF
  ## worker core(s): DOWNLINK_CORE (core list index 1)
  ## HQoS worker(s): HQOS_CORE (core list index 0)
  #
  dev DOWNLINK_PCI {
    workers 1
    hqos { hqos-thread 0 }
  }
}

logging {
  ## Available severity levels:
  ## emerg|alertcrit|err|warn|notice|info|debug|disabled

  default-log-level info
  default-syslog-log-level info
}
