set interface ip address UPLINK_INTERFACE_NAME 10.0.0.0/16
set interface state UPLINK_INTERFACE_NAME up
exec bulk_configs/ul/ip_neighbours.conf
blocklist set UPLINK_INTERFACE_NAME enable
exec bulk_configs/ul/bulk_block_rules.conf
flowtable_qinq intf UPLINK_INTERFACE_NAME
exec bulk_configs/ul/bulk_qinq_flows.conf
bng_policer intf UPLINK_INTERFACE_NAME
exec bulk_configs/ul/bulk_policer_rules.conf

set interface ip address DOWNLINK_INTERFACE_NAME 10.1.0.0/16
set interface state DOWNLINK_INTERFACE_NAME up
exec bulk_configs/dl/ip_neighbours.conf
allowlist set DOWNLINK_INTERFACE_NAME enable
exec bulk_configs/dl/bulk_allow_rules.conf
flowtable_ip4 intf DOWNLINK_INTERFACE_NAME
exec bulk_configs/dl/bulk_ip4_flows.conf
encap qinq-pppoe intf DOWNLINK_INTERFACE_NAME
exec bulk_configs/dl/bulk_encap_qinq.conf
